### ISSUE TITLE
Communication between Webview and Deno is impossible

### ISSUE THREAD

**Issue by RufusWein** [webview/webview_deno#70] opened 2021-01-10 17:36 UTC
I had using via XMLhttpRequest, dosent work, via webview.eval, dont send result operation only true or false

I work with **Done v1.6.3**, **Webview v0.5.5**, on **Windows 10**

**Comment by eliassjogreen** [comment] 2021-01-10 18:46
Closing as duplicate of #68

**Closed by eliassjogreen** 2021-01-10 18:46 UTC
