### ISSUE TITLE
Rendering performance issues vs Chrome/Safari

### ISSUE THREAD

**Issue by parliament718** [webview/webview_deno#35] opened 2020-06-11 12:01 UTC
For the past week I've been porting my Electron app to Deno w/ deno_webview.

My app is for building trading strategies and uses heavy charting using D3.js/Canvas. Zooming/panning performance is critical here.

I'm observing deno_webview have worse performance in that area. Here's a video demonstrating the same app running in deno_webview on the left, v.s. Chrome and Safari on the right. 

https://drive.google.com/file/d/1HxPPFh4sPXhOwvBg07KglzZYJN8u1p3l/view?usp=sharing

Chrome/Safari are noticably smoother. Additonally, the rendered lines in chrome/safari are sharper. It may be hard to see in the video but the rendering is a little blurred in deno_webview (this is the lesser issue, performance is more important)

Unfortunately, this is a show-stopper for me as it would make no sense to continue porting if I can't get on-par rendering performance.

Do you know why this is happening? Deno_webview internals are a bit over my head.

Thank you

**Comment by eliassjogreen** [comment] 2020-06-11 21:19
This is most likely because it uses the OS's internal web browser which would impact performance compared to chrome. Why it is slower on safari is weird due to safari being the internal browser engine but it has more to do with the C bindings than this. Could potentially be fixed by #28

**Comment by parliament718** [comment] 2020-06-12 11:53
I've provided a test harness for this. I hope it helps to investigate the issue.

[webview-performance.zip](https://github.com/eliassjogreen/deno_webview/files/4770575/webview-performance.zip)

cd client && npm install && npm run start
cd server && deno run -A --unstable webview.ts

**Comment by Patbox** [comment] 2021-04-05 17:12
I can confirm webview being really slow on Linux too.

**Comment by davecaruso** [comment] 2021-05-05 00:54
i was testing this out (on linux), and i got what feels like <10fps when viewing deno.land.

i was playing around and it seems when you increase the delta value (second parameter for `run()`), the webview runs faster. this feels like the webview is supposed to be the only thing running on it's thread. i don't know the internals of this but maybe the actual webview
could be on a separate thread, but that doesnt sound easy to implement.

for now i might mess around with workers as that does something similar, but it might be better to do in the plugin itself.

**Comment by eliassjogreen** [comment] 2022-01-27 02:43
This is probably (?) no longer an issue as we have switched to the official webview bindings now...

**Closed by eliassjogreen** 2022-01-27 02:43 UTC
Labels: macos
