### ISSUE TITLE
Deno.openPlugin is not a function

### ISSUE THREAD

**Issue by justinmchase** [webview/webview_deno#96] opened 2021-11-27 00:23 UTC
With the default example code and the latest version of Deno I get:

> error: Uncaught (in promise) TypeError: Deno.openPlugin is not a function
>  return Deno.openPlugin(file.path);

**Comment by brandonros** [comment] 2021-11-27 20:07
looks like this package is using https://github.com/denosaurs/plug but v0.2.9 but that package is up to v0.4.1

**Comment by justinmchase** [comment] 2021-11-29 21:09
So I took a crack at updating the dependency, the rust components build locally just fine but the problem is that the deno api isn't just a little different but drastically different.

It appears fairly straight forward, especially if you already know how this library is working, but it was a little bigger of a change than I was able to make on a weekend project.

But here is the summary of my discoveries in case anyone else is gonna take this on:

Relevent Docs
- [Foreign Function Interface](https://deno.land/manual@v1.16.3/runtime/ffi_api)
- [deno_bindgen](https://github.com/littledivy/deno_bindgen)

1. Probably dump the plugin library entirely
2. Use `Deno.dlopen` to load the binary
3. Modify all of the rust apis to use the `#[deno_bindgen]` probably
4. Modify the wrapper functions to pass the right inputs based on the new FFI api

The bindgen repo has examples for strings and structs, etc. I think its the way to go but would require some hefty refactoring it seems.

**Comment by brandonros** [comment] 2021-11-29 22:09
I tried the same thing and got stuck that the "new" Deno FFI API only allows Buffers and u8/u16/u32 basically...

I tried to set up the symbols (which the Plug package wants) given the function names and all that but I agree with you, I think deno_bindgen will be needed because... oddly... by design Deno FFI doesn't support structs yet?

**Comment by justinmchase** [comment] 2021-11-30 14:20
yeah and the numbers are easy to convert but the strings require some wrapper to convert to buffers and likely something on the native side to make sure its converting the buffer to a string properly.

**Comment by eliassjogreen** [comment] 2021-11-30 15:35
Im working on [deno#12828](https://github.com/denoland/deno/pull/12828) which should enable everything that is required for `webview_deno` to work once again, plug is updated and should work so now its just a matter of finishing my pr.

**Comment by brandonros** [comment] 2021-11-30 15:37
@eliassjogreen Happy to hear it. Thank you very much for what you are doing.

Will it look somewhat like this: https://github.com/node-ffi-napi/ref-struct-di ?

**Comment by brandonros** [comment] 2021-12-15 17:18
https://github.com/denoland/deno/pull/12828/files landed. Sounds like we need to wait for v1.17.0 to come out of Deno, then for Elias to update https://github.com/denosaurs/plug and then pull those changes into this repo, then also update this repo for the new FFI format.

**Comment by matteoturini** [comment] 2022-01-08 15:55
Still blocked?

**Comment by eliassjogreen** [comment] 2022-01-08 16:29
#99 Yep, kind of

**Closed** 2022-01-26 22:54 UTC

**Comment by justinmchase** [comment] 2022-01-27 03:19
YESS
![YESSS](https://user-images.githubusercontent.com/10974/151286053-33d54d2d-3b97-4706-99fc-1456db08fa78.gif)
